### ISSUE TITLE
[BUG/Feature request] ogg files should work by default but the app does not pick them up when scanning 

### ISSUE THREAD

**Issue by god-damnit** [muzik-apps/Muzik-offline#53]
**Is your feature request related to a problem? Please describe.**
->Can't play music stored in formats other than mp3

**Describe the solution you'd like**
->Support for other music formats :D

**Describe alternatives you've considered**
->Converting the music files but it takes a lot of time and some songs lose their metadata

**Additional context**
->None

**Comment by waveyboym** [comment]
@god-damnit , I just want to confirm, the error you are seeing, is it that the app itself cannot pick up your ogg files and not that ogg files cannot be played?

But either way, you shouldn't have to convert the files from ogg to mp3 as ogg should, by default, work. I will have a look into this.

**Comment by god-damnit** [comment]
@waveyboym App doesn't detect ogg files for me, i have to convert them

**Comment by waveyboym** [comment]
@god-damnit, Ok I see. Thank you for the information. I will try to have a fix out sometime(hopefully) before the end of this week in the next major release.

**Comment by waveyboym** [comment]
@god-damnit release here fixes the issue: https://github.com/muzik-apps/muzik-offline/releases/tag/v0.4.0
If you use Linux, a release for that will come out in a bit. If you use macos, that will have to wait for a while.
If you encounter any issues again, please don't mind opening up another issue. 
Thank you for taking the time to point out this issue.
